### ISSUE TITLE
Error on trying to install any ipk, Never had homebrew on my TV before

### ISSUE THREAD

**Issue by RonyMane** [throwaway96/dejavuln-autoroot#14]
An error occurred during the installation. Reason: Unable to get local issuer certificate. I am not sure why since this is my first time with the homebrew or anything of the sort. Does anyone know a work around or an alternative repository?

**Comment by rcuevaspantoja** [comment]
same here, my TV wasnt rooted or anything. After the procees the homebrew app shows up but i cant install anything

**Comment by Slyszer** [comment]
> An error occurred during the installation. Reason: Unable to get local issuer certificate. I am not sure why since this is my first time with the homebrew or anything of the sort. Does anyone know a work around or an alternative repository?

What year was the TV build?
Which Web OS version is it running and does it have the 04.40.xx software update installed? If so the firmware could be patched already which gives errors when trying to root the TV.

**Comment by throwaway96** [comment]
Not related to dejavuln-autoroot. See webosbrew/webos-homebrew-channel#179.
