### ISSUE TITLE
missing signature file

### ISSUE THREAD

**Issue by Temik007** [throwaway96/dejavuln-autoroot#16]
Hello! I try it on OLED65B9PLA 05.40.45

LOG:
`[ ] hi`
`[ ] script path: /tmp/usb/sda/sda1/autoroot.sh`
`[ ] date: 2024-08-08 20:41:47 UTC`
`[ ] id: uid=0(root) gid=0(root) groups=0(root),10(wheel),506(pulse-access),509(se),777(crashd)`
`[ ] webOS version: 4.10.0`
`[ ] devmode_enabled is already a directory; is your TV already rooted?`
`[ ] Installing /tmp/autoroot.YkFxU0/hbchannel.ipk...`
`[ ] Rooting complete`
`[ ] Current firmware verifies start-devmode.sh signature`
`[ ] start-devmode.sh verification failed: missing signature file`

How to fix this? Thanks!

**Comment by Temik007** [comment]
reset to default settings fix this!

**Comment by M0nk3yOo** [comment]
May you give me a hint which default you are talking from? From TV, or sth else?
Was the effect that the TV was not rooted anymore after a reboot?
