### ISSUE TITLE
Cant play .mp3

### ISSUE THREAD

**Issue by pivoivo** [throwaway96/dejavuln-autoroot#2]
For me it always says "This file cannot be recognised". Tried with NTFS and FAT32. Firmware 06.10.30

**Comment by GiveMeTheBits** [comment]
I had the same on  my first attempt until I move the repo's zip contents to the root of the usb drive, not within a folder as it does when extracted. I also add the autroroot.debug file at the same time just to catch errors on the next attempt, but it ran on my 2nd try.

Worked on oled77c2pua
WebOS 7.2.0-35 Mullet-marine
Software 03.20.95

**Comment by throwaway96** [comment]
@pivoivo

You didn't provide enough information, so I'll just assume you have webOS 3.5. Try version 0.0.2 or later.

**Comment by pivoivo** [comment]
Worked with Version 0.0.3 
Thanks a lot!
